name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_NAME=${{ github.event.repository.name }}
        docker build . \
          --file Dockerfile \
          --tag $IMAGE_NAME:latest \
          --tag $IMAGE_NAME:${{ github.ref_name }}-$(date +%s)
