name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
      TAG_LATEST: latest
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME:$TAG_LATEST \
            --tag $IMAGE_NAME:$TAG_DYNAMIC

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:$TAG_LATEST
          docker push $IMAGE_NAME:$TAG_DYNAMIC
