name: Automated review

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: NPM CI
        run: npm i
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run prettier check
        run: npm run check
