name: Automated review

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: NPM CI
        run: npm install
           
      #- name: Run prettier check
      #  run: npm run check

  test:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:

      - uses: actions/checkout@v4

      - name: NPM CI
        run: npm install
      
      - run: npm test

  build-container:
    needs: quality-check
    runs-on: ubuntu-latest
    env:
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag angulartodos_app:$TAG_DYNAMIC \
          --tag tag angulartodos_app:latest

      - name: wohin
      
